### ISSUE TITLE
New line after display

### ISSUE THREAD

**Issue by khalilsarwari** [Cal-CS-61A-Staff/dart_scheme#34]
Missing new line
![screen shot 2018-04-08 at 9 48 29 pm](https://user-images.githubusercontent.com/20780564/38479897-1135903c-3b77-11e8-8231-f174d0605664.png)

**Comment by jathak** [comment]
This is the intended behavior. Use `(newline)` to output a new line.

[61A Scheme Spec](https://cs61a.org/articles/scheme-primitives.html#display)
[R5RS](http://www.schemers.org/Documents/Standards/R5RS/HTML/r5rs-Z-H-9.html#%_sec_6.6.3)
