### ISSUE TITLE
Multiline code breaks up arrow history functionality

### ISSUE THREAD

**Issue by jalagar** [Cal-CS-61A-Staff/dart_scheme#42]
Example:
```
scm> (+ 1 2)
3
scm> (
)
()
scm> # up arrow takes me to the multi line ( )s but I can't get to the first expression anymore
```

**Comment by jathak** [comment]
Hold Ctrl to scroll through multi-line history items.

Also, RTFM (and by manual I mean the "Keyboard Shortcuts" section of the message that's displayed when you open the interpreter)

**Comment by jathak** [comment]
It was only added in the rewrite last semester. The old interpreter stored each line as a separate history entry.

**Comment by swathugala** [comment]
+1
Literally just had this same conversation with Jen IRL 😂

**Comment by swathugala** [comment]
Though actually - can there be a line mentioning that it's command for Mac users?

**Comment by jathak** [comment]
I think it should be Ctrl regardless of platform (neither the [Dart docs](https://api.dartlang.org/stable/1.24.3/dart-html/KeyEvent/ctrlKey.html) nor the [web api docs](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey) seem to indicate the property I'm using being dependent on platform)
