### ISSUE TITLE
Can't copy and paste prior output 

### ISSUE THREAD

**Issue by jalagar** [Cal-CS-61A-Staff/dart_scheme#53]
Not sure if this worked before or not, but I can't select text and hit command-c and command-v. Did this just never work?

**Comment by jathak** [comment]
Hmm. It works for me only Chrome OS. I'm guessing this is related to #49.

**Comment by jalagar** [comment]
Not quite, it listens sometimes but when I paste it erases all the output. I dm'd you a video
