### ISSUE TITLE
Suggestion: rename call/cc -> call/ec

### ISSUE THREAD

**Issue by kpengboy** [Cal-CS-61A-Staff/dart_scheme#82]
I would suggest that `call/cc` should be renamed `call/ec`, and `callWithCurrentContinuation` similarly to `callWithEscapeContinuation`, since that's what it really is in this implementation.

**Comment by jathak** [comment]
Yeah, that's correct. Given, it's not covered in 61A and was never properly implemented, I removed it in #76.
