### ISSUE TITLE
Visualize is broken?

### ISSUE THREAD

**Issue by pbitutsky** [Cal-CS-61A-Staff/dart_scheme#85]
On https://scheme.cs61a.org/, `visualize` seems to be broken.

When running the command `(visualize (define x 5))`, I get the error message 

```
TypeError: Instance of 'minified:tp&lt;dynamic, dynamic&gt;': type 'minified:tp&lt;dynamic, dynamic&gt;' is not a subtype of type 'minified:et&lt;minified:l, minified:c&gt;'
```

**Comment by jathak** [comment]
Whoops! Fixed this type error locally a while ago but forgot to actually commit it. #86 should fix this

**Comment by jathak** [comment]
Fix should be deployed now
